service: management-aws-info-server

custom: ${file(config/config.${self:provider.stage}.yml)}

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, self:custom.defaultRegion}
  logRetentionInDays: ${self:custom.logRetentionInDays, 14}
  deploymentBucket:
    name: ${self:custom.deployBucket}
    serverSideEncryption: AES256
  deploymentPrefix: serverless
  tracing:
    apiGateway: ${self:custom.tracing.apiGateway, false}
    lambda: ${self:custom.tracing.lambda, false}
  tags: ${file(config/tags.${self:provider.stage}.yml)}

functions:
  listUsers:
    handler: src/iam/handler.listUsers
    events:
      - http:
          path: iam/users
          method: get

plugins:
  - serverless-offline
  - serverless-mocha-plugin
